# Generated by Django 2.2.7 on 2023-07-04 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='current_floor',
            new_name='floor',
        ),
    ]
