# Generated by Django 2.2.7 on 2023-07-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20230704_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floor',
            name='floor',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
