# Generated by Django 2.2.7 on 2023-07-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_elevator_current_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatorrequest',
            name='request_floor',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
