# Generated by Django 2.2.7 on 2023-07-04 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230704_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='floor',
            name='assigned',
            field=models.BooleanField(default=False),
        ),
    ]
