# Generated by Django 2.2.7 on 2023-07-05 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_floor_assigned'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Floor',
        ),
    ]
