# Generated by Django 2.2.7 on 2023-07-05 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='current_status',
        ),
    ]
